name: CI

on:
  pull_request:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true
      - name: gofmt
        run: |
          files=$(gofmt -l .)
          if [ -n "$files" ]; then
            echo "$files"
            exit 1
          fi
      - run: go test ./... -v
      - run: go build ./...
